name: geo

channels:
  - conda-forge

dependencies:
  - python=3.11
  - geopandas
  - geopy
  - jupyterlab
  - jupyterlab-git
  - mamba
  - mapclassify
  - matplotlib
  - momepy
  - osmnx
  - owslib
  - pandas<2.1.0
  - pysal
  - r5py>=0.1.1.dev0
  - pip
  - pip:
      - r5py.sampledata.helsinki>=0.1.1.dev0
      - r5py.sampledata.sao_paulo>=0.1.1.dev0
